import {
  Bell,
  FileEdit,
  HelpCircle,
  Image,
  LayoutDashboard,
  Package,
  Sparkles,
} from 'lucide-react'

export const backOfficeNavItems = [
  {
    to: '/manage',
    icon: LayoutDashboard,
    title: 'Overview',
    desc: 'ພາບລວມຂອງຫນ້າຈັດການ',
    eyebrow: 'Control Hub',
    color: 'text-slate-700',
    bg: 'bg-slate-100',
    accent: 'from-slate-400 via-slate-600 to-slate-900',
    enabled: true,
  },
  {
    to: '/settings/line',
    icon: Bell,
    title: 'ຈັດການ LINE ແຈ້ງເຕືອນ',
    desc: 'ກໍານົດຜູ້ຮັບ, ຈັດການ broadcast ແລະ ຕິດຕາມການແຈ້ງເຕືອນ.',
    eyebrow: 'Notifications',
    color: 'text-amber-600',
    bg: 'bg-amber-50',
    accent: 'from-amber-400 via-orange-400 to-amber-600',
    enabled: true,
  },
  {
    to: '/manage/promotions',
    icon: Sparkles,
    title: 'ຕັ້ງຄ່າໂປຣໂມຊັນ',
    desc: 'ຈັດການ Buy 1 Get 1, ຂອງແຖມ, ແລະ promo code ໃຫ້ກົງກັບຫນ້າຂາຍ.',
    eyebrow: 'Campaigns',
    color: 'text-blue-600',
    bg: 'bg-blue-50',
    accent: 'from-sky-400 via-blue-500 to-indigo-600',
    enabled: true,
  },
  {
    to: '/manage/images',
    icon: Image,
    title: 'ຈັດການຮູບສິນຄ້າ',
    desc: 'ອັບໂຫຼດ, ປັບປຸງ, ແລະ ກວດກາຮູບພາບສິນຄ້າທີ່ສະແດງໃນ POS.',
    eyebrow: 'Catalog',
    color: 'text-emerald-600',
    bg: 'bg-emerald-50',
    accent: 'from-emerald-400 via-green-500 to-teal-600',
    enabled: true,
  },
  {
    to: '/manage/help',
    icon: FileEdit,
    title: 'ຕັ້ງຄ່າ Help',
    desc: 'ແກ້ໄຂຫົວຂໍ້, ເນື້ອໃນ, ແລະ ຄູ່ມືທີ່ໃຫ້ທີມງານໃຊ້ອ້າງອີງ.',
    eyebrow: 'Knowledge Base',
    color: 'text-orange-600',
    bg: 'bg-orange-50',
    accent: 'from-orange-400 via-amber-500 to-red-500',
    enabled: true,
  },
  {
    to: '/help',
    icon: HelpCircle,
    title: 'ຊ່ວຍເຫຼືອ & ຄູ່ມື',
    desc: 'ເຂົ້າຫາຄູ່ມືການໃຊ້ງານ, FAQ, ແລະ ເອກະສານອ້າງອີງໄດ້ທັນທີ.',
    eyebrow: 'Support',
    color: 'text-violet-600',
    bg: 'bg-violet-50',
    accent: 'from-violet-400 via-fuchsia-500 to-violet-600',
    enabled: true,
  },
  {
    to: '#',
    icon: Package,
    title: 'ຂໍ້ມູນສິນຄ້າເພີ່ມເຕີມ',
    desc: 'ສ່ວນນີ້ຈະໃຊ້ສຳລັບຈັດການ metadata, ຫມວດໝູ່, ແລະ ລາຍລະອຽດເພີ່ມ.',
    eyebrow: 'Coming Soon',
    color: 'text-slate-400',
    bg: 'bg-slate-100',
    accent: 'from-slate-300 via-slate-400 to-slate-500',
    enabled: false,
  },
]

export const backOfficeModuleItems = backOfficeNavItems.filter((item) => item.to !== '/help')
