import {
  Banknote,
  BarChart3,
  Bell,
  Boxes,
  CalendarRange,
  FileEdit,
  HelpCircle,
  Image,
  LayoutDashboard,
  PackageMinus,
  Sparkles,
  Target,
  Wrench,
} from 'lucide-react'

export const backOfficeNavItems = [
  {
    to: '/manage',
    icon: LayoutDashboard,
    title: 'ພາບລວມ',
    desc: 'ສະຫຼຸບຫຍໍ້ຂອງມື້ນີ້ ແລະ ທາງລັດເຂົ້າຫາທຸກ module.',
    eyebrow: 'Overview',
    group: 'ລາຍງານ',
    color: 'text-slate-700',
    bg: 'bg-slate-100',
    accent: 'from-slate-400 via-slate-600 to-slate-900',
    enabled: true,
  },
  {
    to: '/manage/sales',
    icon: BarChart3,
    title: 'ສະຫຼຸບຍອດຂາຍ',
    desc: 'ຕິດຕາມການເຄື່ອນໄຫວການຂາຍ: ຍອດລວມ, ບິນ, ສິນຄ້າຂາຍດີ, ພະນັກງານ.',
    eyebrow: 'Sales Report',
    group: 'ລາຍງານ',
    color: 'text-blue-600',
    bg: 'bg-blue-50',
    accent: 'from-sky-400 via-blue-500 to-indigo-600',
    enabled: true,
  },
  {
    to: '/manage/monthly',
    icon: CalendarRange,
    title: 'ສະຫຼຸບຍອດຂາຍປະຈຳເດືອນ',
    desc: 'ຍອດຂາຍຈິງ vs ເປົ້າ ຕໍ່ພະນັກງານ (ບາດ): Ach%, Req/Day, YTD.',
    eyebrow: 'Monthly vs Target',
    group: 'ລາຍງານ',
    color: 'text-indigo-600',
    bg: 'bg-indigo-50',
    accent: 'from-indigo-400 via-blue-500 to-violet-600',
    enabled: true,
  },
  {
    to: '/manage/stock',
    icon: Boxes,
    title: 'ເຄື່ອນໄຫວ Stock',
    desc: 'ຮັບເຂົ້າ-ຈ່າຍອອກ ປະຈຳວັນ/ອາທິດ/ເດືອນ, ແນະນຳເຕີມ stock ແລະ ສິນຄ້າຄ້າງ.',
    eyebrow: 'Stock Report',
    group: 'ລາຍງານ',
    color: 'text-teal-600',
    bg: 'bg-teal-50',
    accent: 'from-teal-400 via-emerald-500 to-green-600',
    enabled: true,
  },
  {
    to: '/manage/targets',
    icon: Target,
    title: 'ກຳນົດເປົ້າຂາຍ',
    desc: 'ຕັ້ງເປົ້າຂາຍພະນັກງານແຕ່ລະເດືອນ ເປັນເງິນບາດ (฿).',
    eyebrow: 'Sales Targets',
    group: 'ຈັດການຮ້ານ',
    color: 'text-rose-600',
    bg: 'bg-rose-50',
    accent: 'from-rose-400 via-pink-500 to-red-500',
    enabled: true,
  },
  {
    to: '/manage/promotions',
    icon: Sparkles,
    title: 'ຕັ້ງຄ່າໂປຣໂມຊັນ',
    desc: 'ຈັດການ Buy 1 Get 1, ຂອງແຖມ, ແລະ promo code ໃຫ້ກົງກັບຫນ້າຂາຍ.',
    eyebrow: 'Campaigns',
    group: 'ຈັດການຮ້ານ',
    color: 'text-violet-600',
    bg: 'bg-violet-50',
    accent: 'from-violet-400 via-purple-500 to-indigo-600',
    enabled: true,
  },
  {
    to: '/manage/parts',
    icon: Wrench,
    title: 'ສິນຄ້າອາໄຫຼ່',
    desc: 'ຍອດຄົງເຫຼືອ, ລາຄາຂາຍ ແລະ ອາໄຫຼ່ໃຊ້ກັບສິນຄ້າຕົວໃດ.',
    eyebrow: 'Spare Parts',
    group: 'ລາຍງານ',
    color: 'text-slate-600',
    bg: 'bg-slate-100',
    accent: 'from-slate-400 via-slate-500 to-slate-700',
    enabled: true,
  },
  {
    to: '/manage/minstock',
    icon: PackageMinus,
    title: 'Minimum Stock',
    desc: 'ກຳນົດຈຳນວນຂັ້ນຕ່ຳຕໍ່ສິນຄ້າ ແລະ ແຈ້ງເຕືອນ LINE ເມື່ອຕ່ຳກວ່າກຳນົດ.',
    eyebrow: 'Reorder Point',
    group: 'ຈັດການຮ້ານ',
    color: 'text-cyan-600',
    bg: 'bg-cyan-50',
    accent: 'from-cyan-400 via-sky-500 to-blue-600',
    enabled: true,
  },
  {
    to: '/manage/images',
    icon: Image,
    title: 'ຈັດການຮູບສິນຄ້າ',
    desc: 'ອັບໂຫຼດ, ປັບປຸງ, ແລະ ກວດກາຮູບພາບສິນຄ້າທີ່ສະແດງໃນ POS.',
    eyebrow: 'Catalog',
    group: 'ຈັດການຮ້ານ',
    color: 'text-emerald-600',
    bg: 'bg-emerald-50',
    accent: 'from-emerald-400 via-green-500 to-teal-600',
    enabled: true,
  },
  {
    to: '/settings',
    icon: Banknote,
    title: 'ຕັ້ງຄ່າລະບົບ / ເລດເງິນ',
    desc: 'ຕັ້ງເລດແລກປ່ຽນ ₭/฿ ທີ່ໃຊ້ໃນລາຍງານ ແລະ ໜ້າຂາຍ.',
    eyebrow: 'System',
    group: 'ລະບົບ',
    color: 'text-emerald-600',
    bg: 'bg-emerald-50',
    accent: 'from-emerald-400 via-teal-500 to-cyan-600',
    enabled: true,
  },
  {
    to: '/settings/line',
    icon: Bell,
    title: 'LINE ແຈ້ງເຕືອນ',
    desc: 'ກໍານົດຜູ້ຮັບ, ຈັດການ broadcast ແລະ ຕິດຕາມການແຈ້ງເຕືອນ.',
    eyebrow: 'Notifications',
    group: 'ລະບົບ',
    color: 'text-amber-600',
    bg: 'bg-amber-50',
    accent: 'from-amber-400 via-orange-400 to-amber-600',
    enabled: true,
  },
  {
    to: '/manage/help',
    icon: FileEdit,
    title: 'ຕັ້ງຄ່າ Help',
    desc: 'ແກ້ໄຂຫົວຂໍ້, ເນື້ອໃນ, ແລະ ຄູ່ມືທີ່ໃຫ້ທີມງານໃຊ້ອ້າງອີງ.',
    eyebrow: 'Knowledge Base',
    group: 'ລະບົບ',
    color: 'text-orange-600',
    bg: 'bg-orange-50',
    accent: 'from-orange-400 via-amber-500 to-red-500',
    enabled: true,
  },
  {
    to: '/help',
    icon: HelpCircle,
    title: 'ຊ່ວຍເຫຼືອ & ຄູ່ມື',
    desc: 'ເຂົ້າຫາຄູ່ມືການໃຊ້ງານ, FAQ, ແລະ ເອກະສານອ້າງອີງໄດ້ທັນທີ.',
    eyebrow: 'Support',
    group: 'ລະບົບ',
    color: 'text-sky-600',
    bg: 'bg-sky-50',
    accent: 'from-sky-400 via-cyan-500 to-sky-600',
    enabled: true,
  },
]

export const backOfficeNavGroups = ['ລາຍງານ', 'ຈັດການຮ້ານ', 'ລະບົບ']

export const backOfficeModuleItems = backOfficeNavItems.filter((item) => item.to !== '/help')
